name: healthcare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'


dependencies:
  connectivity_plus: ^5.0.2
  google_fonts: ^6.2.1
  appwrite: ^14.0.0
  flutter_markdown: ^0.6.18
  groq: ^1.0.0
  flutter_svg: ^2.0.17
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  file_picker: ^9.2.3
  path: ^1.8.3
  google_maps_flutter: ^2.12.3
  provider: ^6.1.1
  flutter_pdfview: ^1.3.2
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  http: ^1.2.0
  visibility_detector: ^0.4.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



dependency_overrides:
  flutter_web_auth_2: ^4.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
